config/routes.rb
Rails.application.routes.draw do
     devise_for :users
     root to: 'homes#top'
	 get 'home/about' => 'homes#about', as:'homes_about'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :books, only: [:create, :index, :show, :edit, :destroy, :update]
 resources :users, only: [:show, :edit, :index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true, length: { maximum: 200 }
    validates :body, presence: true, length: { maximum: 200 }


	belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
	validates :name, presence: true, length: { minimum: 2, maximum:20 }
	validates :introduction, length: { maximum:50 }

    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  before_action :configure_permitted_parameters, if: :devise_controller?

	  def after_sign_in_path_for(resource)
	  	user_path(current_user.id)
	  end

	  def after_sign_out_path_for(resource)
      root_path
      end


  protected
  def configure_permitted_parameters
  	added_attrs = [ :email, :user_name, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
  	@books = Book.all
    @book_new = Book.new
  end

  def show
  	@book = Book.find(params[:id])
    @book_new = Book.new
    @user = User.find_by(id: @book.user_id)
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path
  end

  def create
     @books = Book.all
  	 @book_new = Book.new(book_params)
     @book_new.user_id = current_user.id
  	if @book_new.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book_new)
    else
      render :index
    end
  end

  def edit
  	@book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to books_path
  end
end

  def update
  	@book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "Book was successfully update."
       redirect_to book_path(@book)
    else
      render :edit
    end
  end

  private

  def book_params
	  params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
	def about
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

	def index
		@books = Book.all
		@book_new = Book.new
    @users = User.all
    @user = current_user
	end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
  end
end

  def update
	  @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
	  end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class= "body">
  <% if flash[:notice] %>
  <div class="flash"><%= flash[:notice] %></div>
<% end %>
  <div class="col-xs-3" >
    <div>
      <h2>User info</h2>
      <div class="user-edit-image">
        <%= attachment_image_tag user, :profile_image, size:'50x50', class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
      </div>
    </div>

    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <th><%= user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= user.introduction %></th>
        </tr>
      </tbody>
    </table>
    <div class="row">
      <%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench"%>
    </div>
    <div>
      <h2>New book</h2>
      <%= form_for book do |f|%>
        <p>text</p>
        <%= f.text_field :title, class: "col-xs-12 book_title" %>
        <p>opinion</p>
        <%=f.text_area :body, class: "col-xs-12 book_body" %>

        <%= f.submit "Create Book", class: "btn btn-primary col-xs-12"%>
      <% end %>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<% if flash[:notice] %>
	<div class="flash">
		<%= flash[:notice] %>
	</div>
<% end %>
<% if @book.errors.any? %>
  <div class="alert alert-warning">
     <ul>error
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
     </ul>
  </div>
<% end %>
<div class="body">
  <div class= "container">
   <div class="row">
    <div class="col-md-6 col-md-offset-3">
     <h1>Editing Book</h1>
       <%= form_for(@book) do |f| %>
        <h4>title</h4>
          <%= f.text_field :title, class: "col-xs-12 book_title" %>
        <h4>Opinion</h4>
          <%= f.text_area :body, class: "col-xs-12 book_body" %>
          <%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
       <% end %>
　　　    <%=link_to "Show", book_path(@book) %>

　　　    <%=link_to "Back", books_path%>
   </div>
  </div>
 </div>
</div>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<% if @book_new.errors.any? %>
  <div class="alert alert-warning">
    <ul>error
      <% @book_new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <%=render 'books/list' ,book: @book_new, user: current_user%>
     <div class="col-xs-9">
      <table class="table table-striped">
        <h1>Books</h1>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%=link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, size:'50x50', class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%=render 'books/list' ,book: @book_new, user: @user %>
<div class="container">
  <div class="row">
    <div class="col-xs-9">
      <table class="table table-striped">
      <h1>Book detail</h1>
        <tbody>
          <tr>
            <td><%=link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, size:'50x50', class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
                <br>
                <%= @user.name %>
                <% end %>
            </td>
              <td><%=link_to @book.title,book_path(@book.id) %></td>
              <td><%= @book.body %></td>

              <% if @book.user_id == current_user.id %>
                <td><%=link_to "Edit", edit_book_path, class: "btn btn-success" %></td>
                <td><%=link_to "Destroy", book_path,method: :delete, "data-confirm" => "本当に削除しますか", class: "btn btn-danger" %></td>
              <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class= "body">
	<div class="container">
		<div class= "top-message col-md-offset3 col-md-6">
			<h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
		</div>
	</div>
</div>

app/views/homes/top.html.erb
<% if flash[:notice] %>
	<div class="flash">
		<%= flash[:notice] %>
	</div>
<% end %>
<div class= "body">
	<div class="container">
		<div class= "top-message col-md-offset3 col-md-6">
			<h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
			<p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong></p>
			<p>you can share and exchange  your opinions , inpressions , and emotions</p>
			<p>about various books!</p>
		<div class="btn-wrapper">
			<botton type="button" class="btn btn-info col-xs-10 col-xs-offset-1 sign_in">
        		<%= link_to "Log in", new_user_session_path %>
      		</botton>
      		<botton type="button" class="btn btn-success col-xs-10 col-xs-offset-1 sign_up">
        		<%= link_to "Sign UP", new_user_registration_path %>
     	 	</botton>
    	</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navnar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li><%= link_to "Home", user_path(current_user), class: "glyphicon glyphicon-home home" %></li>
              <li><%= link_to "Users", users_path,class: "glyphicon glyphicon-user" %></li>
              <li><%= link_to "Books", books_path, class: "glyphicon glyphicon-book books" %></li>
              <li><%= link_to "logout", destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
              <li><%= link_to "Home", root_path, class: "glyphicon glyphicon-home home" %></li>
              <li><%= link_to "About", homes_about_path, class: "glyphicon glyphicon-link about" %></li>
              <li><%= link_to "sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up"%></li>
              <li><%= link_to "login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <%= yield %>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="body">
<% if flash[:notice] %>
  <div class="flash"><%= flash[:notice] %></div>
<% end %>
<% if @user.errors.any? %>
  <div class="alert alert-warning">
    <ul>error
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-9" >
      <h2>User info</h2>
      <%= form_for (@user) do |f| %>
        <h2>User name</h2>
        <h4>Name</h4>
          <%= f.text_field :name %>
        <h4>image</h4>
          <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
        <h4>introduction</h4>
          <%= f.text_area :introduction %>
          <%= f.submit 'Update User' %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/users/index.html.erb
<%=render 'books/list' ,book: @book_new, user: @user%>
<div class="container">
  <div class="row">
    <div class="col-xs-9">
      <table class="table table-striped">
        <h1>Users</h1>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user|  %>
            <tr>
              <td> <%= attachment_image_tag user, :profile_image, size:'50x50', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
               <td><%= user.name %></td>
               <td><%= link_to "Show", user_path(user) %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%=render 'books/list' ,book: @book_new, user: current_user%>
<div class="container">
  <div class="row">
    <div class="col-xs-9">
      <table class="table table-striped">
        <h1>Books</h1>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                 <td>
                <%=link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, size:'50x50', class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
                <% end %>
                 </td>
                 <td><%= link_to book.title, book_path(book) %></td>
                 <td><%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </div>
      </table>
    </div>
  </div>
</div>